### PR TITLE
added nl language pack, inplemented in app.

### PR DESCRIPTION
**Pull request by 00ihsan**
hello,

i have translated everything but not inplemented it in the app. thats up to you.

thanks for the great app!

### CODE REVIEW

**Comment by gdombiak** [comment]
Wow! Great work. Having a Dutch translation is great! I see that only 2 files for translated. To confirm I got everything translated, I use export to locale which will generate a XLIFF file. I then translate the XLIFF file which is easier than working on xcode and then finally import it back.

Let me know if you need help with any of those steps. I can also accept this merge and then create the XLIFF that will include your changes plus what is pending and send it to you. I'm happy to import the translated XLIFF file or accept more PRs. Whatever works best for you.

Thanks,
Gaston

**Comment by 00ihsan** [comment]
You can inport the translations and send me individual files to translate. Since I don’t know xcode that well i want you to do it. 

Its a great app btw.

**Comment by 00ihsan** [comment]
You can send the XLIFF files

**Comment by gdombiak** [comment]
Hey @00ihsan, sorry I went MIA! I attached the XLIFF file for the OctoPod 3.5 that is coming out next week. Let me know if you need more context for some translations.

[nl.xliff.zip](https://github.com/gdombiak/OctoPod/files/4740799/nl.xliff.zip)

 Thanks,
Gaston

**Comment by 00ihsan** [comment]
Hi,

Welcome back!

I am working in vs code but do not know what the structure of the file is. Where do the translations go. Id or source?

Tnx!

**Comment by gdombiak** [comment]
Hey @00ihsan,

[XLIFF](https://en.wikipedia.org/wiki/XLIFF) is an XML based format used for translations. There are many cool translation products that let you open a xliff and track what is translated and what is pending to be translated. If you used any of the free ones online, first make sure that you can save/export the translated XLIFF. I used [this one](https://xliffedit.com/) for the Mac.

**Comment by 00ihsan** [comment]
I have had no time to do more. Maybe implement it and i try to extend the amount of translations?

**Comment by 00ihsan** [comment]
Hi Gaston,

It's bin a while.

The translations are done untill todays commit.
You can merge this branch to main now.

Have a nice day!

**Comment by 00ihsan** [comment]
I tought i'd give it a shot. But on xcode 12 sim it doesnt word and i cant get in to build on the device.

**Comment by 00ihsan** [comment]
Also working in the app. But can't test on my device.

**Comment by gdombiak** [comment]
Hi @00ihsan,

Is the translation updated to latest translation? If so, I can review the PR and merge it for the next release.

Thanks,
Gaston

**Comment by 00ihsan** [comment]
Hi Gaston,

I think so.
If not let me know what to change and I’ll fix it. 

Thanks!

Kind regards,
Ihsan Topcu

**Comment by 00ihsan** [comment]
Hi,

It can be merged now.

**Comment by gdombiak** [comment]
Perfect! Will attempt the merge later today. 

BTW, by any chance could you go to https://developer.apple.com/account/resources/identifiers/list and let me know if you see this identifier: org OctoPod OctoPod watchkitapp ?

Thanks,
Gaston

**Comment by 00ihsan** [comment]
Hi Gaston,

Great news!

I can’t acces the page:


Met vriendelijke groet,
Ihsan Topcu

**Comment by 00ihsan** [comment]
Hi gaston,

Great news!

I can't access the page: image

**Comment by 00ihsan** [comment]
Not going to make it in version 2? 😀

**Comment by gdombiak** [comment]
Thanks @00ihsan for checking that your account does not own that identifier. My chase continues :). I'm now testing this PR and it's looking very good. Below some feedback:

1. Your addition of "Nederlands" language now appears in language selection. Yay!
2. I had to import the XLIFF for OctoPod to start using new translations. Are you ok if I delete that file after I imported the XLIFF? I then use xcode to generate new XLIFF as I add new entries.
3. This text is too long
   1. "Disconnect" = "Verbinding met de printer verbreken";
   2. Disconnect is the text of the button. See screenshot below
4. Many entries are still pending of translation. When I imported XLIFF xcode showed many entries. Below is an example of of a missing translation

Disconnect button on top-right:
Simulator Screen Shot - iPhone 8 - 2021-08-01 at 15 17 25

Examples of missing translations:
Simulator Screen Shot - iPhone 8 - 2021-08-01 at 15 23 51
Simulator Screen Shot - iPhone 8 - 2021-08-01 at 15 24 00
Simulator Screen Shot - iPhone 8 - 2021-08-01 at 15 24 27
Simulator Screen Shot - iPhone 8 - 2021-08-01 at 15 25 20


Would you like me to 
* merge this PR
* Import XLIFF and delete XLIFF
* Give you XLIFF that you can translate missing entries and then share XLIFF back with me for importing it?

Thanks a lot!
Gaston

**Comment by 00ihsan** [comment]
I agree! Its a pleasure working on this project!

**Review by gdombiak — APPROVED** [review]

**Comment by 00ihsan** [comment]
i could not run it on xcode 13 so couldnt test it. btw i dont have payed apple dev program so some features are not available.how to debug on my device?

**Comment by gdombiak** [comment]
Oh, I see. That makes translations harder for sure. I think that with free account you can still run in simulator and I think that Apple recently changed things so you can also install on your phone. Yes, some features like push notifications are only available for paid accounts. In any case, I'm happy to share screenshots of what you need.

This PR has been merged. I will now move XLIFF out of nl.proj folder, import it and then delete it. I will let you know once ready.

Thanks again,
Gaston

**Comment by 00ihsan** [comment]
Thanks Gaston. will see

**Comment by gdombiak** [comment]
We have a Facebook group for translators and we use a google doc to track new entires that need translation. If you want, you can send me an email with your FB account and email so I can share the google doc with you.

Attached is the XLIFF that you can keep using for translation and let me know once you want me to import it. master has now Dutch incorporated which will be included in next release. Make sure to have all Siri intents translated at a minimum so we can do a new release.

Welcome aboard!!!!
Gaston

[nl.xliff.zip](https://github.com/gdombiak/OctoPod/files/6913556/nl.xliff.zip)

**Pull request merged**
