### PR TITLE
Header Support

### PR DESCRIPTION
**Pull request by kadaan**
Support specifying headers for OctoPrint connections so that then can be secured behind a Cloudflare Zero Trust Service Token

### CODE REVIEW

**Comment by gdombiak** [comment]
Hi @kadaan ,

I incorporated this PR into a local branch and been doing some testing. Backwards compatibility is passing. However, I'm facing some challenges with Cloudflare Zero Trust. It seems to be tunneling POST requests as GET requests for some reason. I saw a [recent post](https://community.cloudflare.com/t/cloudflared-tunnel-receives-post-request-as-get/581874) from someone else that also saw this. Let me know if you know of a configuration that I missed. The other thing that it's still not working is websocket connection. I have not analyzed that one yet to know what is going on.

BTW, I noticed that you were expecting a "=" character in the header.  I'm setting this format in the header 

> CF-Access-Client-Id: myblah.access, CF-Access-Client-Secret: mysecretblah

were you using something different? I changed the code to accept both = or : as a separator. I fixed a few minor things as I was testing. 

Thanks for this great contribution.
Gaston

**Comment by kadaan** [comment]
@gdombiak Yeah, I expected `Key1=Value1,...,KeyN=ValueN`. It is probably better to change the `=` to `:`.

**Comment by kadaan** [comment]
@gdombiak No, I am experiencing a POST -> GET issue.  

A couple questions:
1. The websocket connection, what is it requesting?  AFAICT the whole app is working for me?
2. What POST request are you making that is failing?

My configuration is as follows:
1. Tunnel
    1.  Public hostname for octoprint
    2. Public hostname for camera streamer
2. Service token for OctoPod
3. Access Group for OctoPod
4. Application for Octoprint
    1. Policy for regular login
    2. Policy for login using OctoPod service group (must be set to Action = ServiceAuth
5, Application for Camera Streamer
    1. Policy for regular login
    2. Policy for login using OctoPod service group (must be set to Action = ServiceAuth

**Comment by kadaan** [comment]
@gdombiak I checked the code and bed target temp setting seems to be a POST.  That works perfectly for me.

**Comment by gdombiak** [comment]
Found it! I was using HTTP instead of HTTPS. Using HTTPS in the printer hostname I have no issues with websockets or with POST requests. The other thing I found is that connecting to my dev env worked fine but connecting to the real OctoPi required enabling CORS. I will create a wiki page with all settings so others can follow for future setups. 

I will do some more testing before closing this PR and creating one from the branch I created.

Thanks,
Gaston

**Comment by gdombiak** [comment]
@kadaan , I created [this wiki page](https://github.com/gdombiak/OctoPod/wiki/Safely-connect-to-OctoPrint-from-outside-of-your-home-with-Cloudflare-Zero-Trust) to help with the setup. Let me know if you see incorrect or missed things.

Thanks,
Gaston

**Comment by gdombiak** [comment]
PR has been included in new PR https://github.com/gdombiak/OctoPod/pull/674

**Pull request closed without merging**
