### PR TITLE
added new full xliff.

### PR DESCRIPTION
**Pull request by 00ihsan**
Hi Gaston,

I have done it again 😀. 

Please merge import and delete. let me know if there is something.

Whats your mail?

### CODE REVIEW

**Review by gdombiak — APPROVED** [review]
Do not make further changes. I'm importing the new XLIFF

**Comment by 00ihsan** [comment]
Its ok with me.

**Comment by gdombiak** [comment]
Looking very good. Almost there based on my limited testing. Only found these potential pending things unless you want to keep them in English. I highlighted in red.

Simulator Screen Shot - iPhone 8 - 2021-08-01 at 17 54 24
 
Simulator Screen Shot - iPhone 8 - 2021-08-01 at 17 54 31


Simulator Screen Shot - iPhone 8 - 2021-08-01 at 17 52 22


Thanks,
Gaston

PS: I sent you an email to what I think is your email address!

**Comment by 00ihsan** [comment]
Hi Gaston,

Where on Github did you find my mail? 😀 

I have no Facebook (yet) so I’ll look into it. 

I’ll also look into it if im going to use xliff or the doc. 

Thanks for this collaboration. 

Kind regards,
Ihsan Topcu

**Comment by gdombiak** [comment]
https://www.sourcecon.com/how-to-find-almost-any-github-users-email-address/ :D Basically, when you do a commit your email address is stored as part of the events of your github account.

No worries about FB. Reply to my email (if your account) and we can take it from there. If not send me an email to gdombiak at gmail.

Gaston

**Pull request closed without merging**
